services:
  # PostgreSQL database for Kong
  kong-postgres:
    image: postgres:14
    container_name: kong-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ESD213password!
      POSTGRES_DB: kong
    networks:
      - kong-net
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  kong-net:
    driver: bridge
