# Use the official Python image
FROM python:3.9-slim

ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /app

# Copy the current directory to the container
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port for Flask
EXPOSE 5000

# Run the Flask app
CMD ["python", "-u", "notification_service.py"]

