services:
  # PostgreSQL database for Kong
  # kong-postgres:
  #   image: postgres:14
  #   container_name: kong-postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: ESD213password!
  #     POSTGRES_DB: kong
  #   networks:
  #     - kong-net
  #   volumes:
  #     - ./pg-data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  # Kong API Gateway
  kong:
    image: kong:latest
    container_name: kong
    restart: always
    # depends_on:
    #   - kong-postgres
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: 116.15.73.191
      KONG_PG_USER: admin
      KONG_PG_PASSWORD: ESD213password!
      KONG_PG_DATABASE: kong
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_STATUS_LISTEN: 0.0.0.0:8100
    networks:
      - kong-net
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8100:8100"
  
  # kong-migrations:
  #   image: kong:latest
  #   command: kong migrations bootstrap
  #   environment:
  #     KONG_DATABASE: postgres
  #     KONG_PG_HOST: 116.15.73.191
  #     KONG_PG_USER: admin
  #     KONG_PG_PASSWORD: ESD213password!
  #     KONG_PG_DATABASE: kong
  #     KONG_PROXY_LISTEN: 0.0.0.0:8000
  #     KONG_ADMIN_LISTEN: 0.0.0.0:8001
  #     KONG_STATUS_LISTEN: 0.0.0.0:8100
  #   networks:
  #     - kong-net

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - kong-net

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge

volumes:
  prometheus-data:
    
  grafana-data:
    
