FROM python:3.9
ENV PYTHONUNBUFFERED=1
WORKDIR /app/process_appointment
COPY . /app/process_appointment
RUN pip install -r /app/process_appointment/requirements.txt
CMD ["python", "process_appointment.py"]